### ISSUE TITLE
Bug : Unable to resolve restyler@v3

### ISSUE THREAD

**Issue by dswan36** [restyled-io/actions#27]
I saw your your post regarding the depreciation of the GHAPP version of Restyled, and as such I wanted to migrate to the Actions version

However,
I'm getting the following error when trying to run the action on any of my repos
`Error: Unable to resolve action 'restyled-io/restyler@v3', unable to find version 'v3'`
I based it off the script in the readme of this repo, and unless I'm being dense I see nothing wrong with it :shipit: 

Here is an example job: https://github.com/dswan36/SillyLittleFiles/actions/runs/10235656390/job/28316747380?pr=292
And here is the YAML source: https://github.com/dswan36/SillyLittleFiles/blob/restyledGHAPP/.github/workflows/restyled.yml

**Comment by pbrisbin** [comment]
Oh geeze, that README is out of date from when the actions lived in `restyled-io/restyler` and not here. Those those both be `restyled-io/actions@v3`. I've just pushed a fix.

**Comment by dswan36** [comment]
> Oh geeze, that README is out of date from when the actions lived in `restyled-io/restyler` and not here. Those should both be `restyled-io/actions@v3`. I've just pushed a fix.

Whoops! I'm glad I helped you notice that. I didn't even think to cheque the date on it!

**Comment by dswan36** [comment]
![image](https://github.com/user-attachments/assets/eec43488-d7b2-4a9f-8208-ca6440d17435)
Success!
