### ISSUE TITLE
Bug: Conflicting restyler engines lead to failure with 0 net difference

### ISSUE THREAD

**Issue by TheEgghead27** [restyled-io/actions#34]
I work on a project that primarily uses Prettier for consistent formatting, and run the [restyled.io GH Action](https://github.com/stuysu/epsilon/blob/main/.github/workflows/restyled-io.yml) against PRs to the repo.

However, because the restyler first runs `jq` style formatting, then `pretter`, it creates two commits that cancel each other out, leaving me with a failed CI and zero-difference PR: https://github.com/stuysu/epsilon/pull/222

Thank you for an awesome tool!

**Comment by pbrisbin** [comment]
Thanks very much for the report. In this specific case, I'm going to [stop the `jq` restyler from running automatically](https://github.com/restyled-io/restylers/blob/main/jq/info.yaml#L2). We created that before `prettier-json` existed, and this is by the far the most common two restylers that "fight" like this -- we should only have one enabled by default.

However, restyler's conflicting and generating zero-diff PRs is a general scenario we'll need to handle. In the non-GitHub-Actions architecture, we'd check against zero-diff before opening our PR -- but the new example GitHub workflows aren't doing that, so you can end up with this result. I'll have the think about the best way to handle that. Maybe it'll happen less once we resolve the `jq` situation.

**Comment by pbrisbin** [comment]
https://github.com/restyled-io/restylers/pull/811
